### ISSUE TITLE
你好，为什么在win10企业版下面使用docker-compose up安装会失败呢？

### ISSUE THREAD

**Issue by 641221621** [twose/swoole-coroutine-docker#7]
`Windows PowerShell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator>
PS C:\Users\Administrator> H;
PS C:\Users\Administrator> h:
PS H:\> cd H:\docker
PS H:\docker> ls

    目录: H:\docker

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2019/4/17      9:33                mysql
d-----        2019/4/17      9:33                redis
d-----        2019/4/17      9:38                swoole
d-----        2019/4/17      9:33                util
-a----        2019/4/17      9:07           1124 docker-compose.yml

PS H:\docker> docker-compose up
Pulling mysql (twosee/swoole-coroutine:mysql)...
mysql: Pulling from twosee/swoole-coroutine
177e7ef0df69: Pull complete
cac25352c4c8: Pull complete
8585afabb40a: Pull complete
1e4af4996053: Pull complete
c326522894da: Pull complete
9020d6b6b171: Pull complete
55eb37ec6e5f: Pull complete
37f3f3d72fbd: Pull complete
03f098d64268: Pull complete
46a52a54cfe9: Pull complete
202bc662895d: Pull complete
46014f07b258: Pull complete
736c8b9b9f96: Pull complete
690df6200a92: Pull complete
ef8eed385d14: Pull complete
Pulling swoole (twosee/swoole-coroutine:)...
latest: Pulling from twosee/swoole-coroutine
27833a3ba0a5: Pull complete
2d79f6773a3c: Pull complete
f5dd9a448b82: Pull complete
95719e57e42b: Pull complete
c8d2a12cdc54: Pull complete
9dd78e1d9662: Pull complete
44551c7c8e49: Pull complete
559e27fa57de: Pull complete
45ebd10ec4e7: Pull complete
ca8ab5e26880: Pull complete
05bcdcd09cdf: Pull complete
58b8e4db9442: Pull complete
48f24e1cd011: Pull complete
4ff620ca8083: Pull complete
d860eb302c51: Pull complete
321c51c648d7: Pull complete
Pulling redis (twosee/swoole-coroutine:redis)...
redis: Pulling from twosee/swoole-coroutine
177e7ef0df69: Already exists
66ec699db42d: Pull complete
9af6d87fd347: Pull complete
62d170e11208: Pull complete
11090682e442: Pull complete
e082801d238e: Pull complete
60bdd517265c: Pull complete
70d4819ea554: Pull complete
8263a41e21ee: Pull complete
Pulling inotify (twosee/swoole-coroutine:inotify)...
inotify: Pulling from twosee/swoole-coroutine
177e7ef0df69: Already exists
9bf89f2eda24: Pull complete
350207dcf1b7: Pull complete
a8a33d96b4e7: Pull complete
a6bbe73cd4ac: Pull complete
7437bed677a4: Pull complete
224469450987: Pull complete
77146cd968da: Pull complete
1fd14aaf5f1e: Pull complete
3c73c6f205be: Pull complete
8bbfe2e0c433: Pull complete
6e0cd798809a: Pull complete
ad07a86624b2: Pull complete
7a3c9d988d91: Pull complete
7d7f69de90f6: Pull complete
fa7fb5610247: Pull complete
Creating docker_redis_1   ... done
Creating docker_inotify_1 ... done
Creating docker_mysql_1   ... done
Creating docker_swoole_1  ... done
Attaching to docker_inotify_1, docker_redis_1, docker_mysql_1, docker_swoole_1
inotify_1  | /bin/bash: inotify.sh: No such file or directory
mysql_1    | 2019-04-17T01:55:21.933651Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symboli
c-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a fut
ure release.
mysql_1    | 2019-04-17T01:55:21.934075Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.13) starting as pr
ocess 1
docker_inotify_1 exited with code 127
mysql_1    | 2019-04-17T01:55:26.847844Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1    | 2019-04-17T01:55:27.218758Z 0 [ERROR] [MY-010270] [Server] Can't start server : Bind on unix socket: Operat
ion not permitted
mysql_1    | 2019-04-17T01:55:27.218778Z 0 [ERROR] [MY-010258] [Server] Do you already have another mysqld server runnin
g on socket: /var/run/mysqld/mysqld.sock ?
mysql_1    | 2019-04-17T01:55:27.218794Z 0 [ERROR] [MY-010119] [Server] Aborting
inotify_1  | /bin/bash: inotify.sh: No such file or directory
mysql_1    | 2019-04-17T01:55:29.073625Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0
.13)  MySQL Community Server - GPL.
docker_inotify_1 exited with code 127
Exception in thread Thread-17:
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 246, in _raise_for_status
  File "site-packages\requests\models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.30/containers/bec20c8de4a
07ffe9cb8c7b7f86d3d72eca27b3913652310a24fffc19d66959c/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose\cli\log_printer.py", line 233, in watch_events
  File "compose\container.py", line 215, in attach_log_stream
  File "compose\container.py", line 307, in attach
  File "site-packages\docker\utils\decorators.py", line 19, in wrapped
  File "site-packages\docker\api\container.py", line 57, in attach
  File "site-packages\docker\api\client.py", line 385, in _read_from_socket
  File "site-packages\docker\api\client.py", line 296, in _get_raw_response_socket
  File "site-packages\docker\api\client.py", line 248, in _raise_for_status
  File "site-packages\docker\errors.py", line 19, in create_api_error_from_http_exception
  File "site-packages\requests\models.py", line 880, in json
  File "site-packages\requests\models.py", line 828, in content
  File "site-packages\requests\models.py", line 750, in generate
  File "site-packages\urllib3\response.py", line 494, in stream
  File "site-packages\urllib3\response.py", line 442, in read
  File "http\client.py", line 449, in read
  File "http\client.py", line 493, in readinto
  File "site-packages\docker\transport\npipesocket.py", line 209, in readinto
  File "site-packages\docker\transport\npipesocket.py", line 20, in wrapped
RuntimeError: Can not reuse socket after connection was closed.

mysql_1    | 2019-04-17T01:55:36.710910Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_1    | 2019-04-17T01:55:36.828526Z 0 [ERROR] [MY-010270] [Server] Can't start server : Bind on unix socket: Operat
ion not permitted
mysql_1    | 2019-04-17T01:55:36.828639Z 0 [ERROR] [MY-010258] [Server] Do you already have another mysqld server runnin
g on socket: /var/run/mysqld/mysqld.sock ?
mysql_1    | 2019-04-17T01:55:36.829158Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql_1    | 2019-04-17T01:55:39.192350Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0
.13)  MySQL Community Server - GPL.
docker_mysql_1 exited with code 1
docker_inotify_1 exited with code 127
docker_mysql_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
ERROR: Aborting.`

docker-compose.yml

`version: '3.4'
services:
  swoole:
    image: "twosee/swoole-coroutine"
    ports:
      - "9501:9501"
    volumes:
      - H:/docker/swoole:/app/src:rw
    restart: always
    depends_on:
      - mysql
    command: php /app/src/server.php start

  mysql:
    image: "twosee/swoole-coroutine:mysql"
    ports:
      - "9502:3306"
    volumes:
      - H:/docker/mysql/data:/var/lib/mysql:rw
      - H:/docker/mysql/sock:/var/run/mysqld:rw # remove when windows.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: test
      MYSQL_USER: php
      MYSQL_PASSWORD: php_user_password_here
    
  redis:
    image: "twosee/swoole-coroutine:redis"
    ports:
      - "9503:6379"
    volumes:
      - H:/docker/redis/data:/var/lib/redis:rw
    sysctls:
        net.core.somaxconn: 65535
    restart: always

  inotify:
    image: "twosee/swoole-coroutine:inotify"
    volumes:
      - H:/docker/:/app:rw
    restart: always
    environment:
      APP_ENV: dev # or product
    working_dir: /app/util
    command: /bin/bash inotify.sh`

**Comment by twose** [comment]
请看docker-compose文件注释中的`remove when windows.`

**Comment by 641221621** [comment]
老板 回复真快啊，是只删除这一行吗？

**Comment by 641221621** [comment]
- H:/docker/mysql/sock:/var/run/mysqld:rw # remove when windows.

**Comment by 641221621** [comment]
> 请看docker-compose文件注释中的`remove when windows.`

亲。删除了 还是不行 继续报错；

`Windows PowerShell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> H:
PS H:\> cd docker
PS H:\docker> ls


    目录: H:\docker


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2019/4/17      9:33                mysql
d-----        2019/4/17      9:33                redis
d-----        2019/4/17      9:38                swoole
d-----        2019/4/17      9:33                util
-a----        2019/4/17     10:18           1126 docker-compose.yml


PS H:\docker> docker-compose up
Pulling mysql (twosee/swoole-coroutine:mysql)...
mysql: Pulling from twosee/swoole-coroutine
177e7ef0df69: Pull complete
cac25352c4c8: Pull complete
8585afabb40a: Pull complete
1e4af4996053: Pull complete
c326522894da: Pull complete
9020d6b6b171: Pull complete
55eb37ec6e5f: Pull complete
37f3f3d72fbd: Pull complete
03f098d64268: Pull complete
46a52a54cfe9: Pull complete
202bc662895d: Pull complete
46014f07b258: Pull complete
736c8b9b9f96: Pull complete
690df6200a92: Pull complete
ef8eed385d14: Pull complete
Pulling swoole (twosee/swoole-coroutine:)...
latest: Pulling from twosee/swoole-coroutine
27833a3ba0a5: Pull complete
2d79f6773a3c: Pull complete
f5dd9a448b82: Pull complete
95719e57e42b: Pull complete
c8d2a12cdc54: Pull complete
9dd78e1d9662: Pull complete
44551c7c8e49: Pull complete
559e27fa57de: Pull complete
45ebd10ec4e7: Pull complete
ca8ab5e26880: Pull complete
05bcdcd09cdf: Pull complete
58b8e4db9442: Pull complete
48f24e1cd011: Pull complete
4ff620ca8083: Pull complete
d860eb302c51: Pull complete
321c51c648d7: Pull complete
Pulling redis (twosee/swoole-coroutine:redis)...
redis: Pulling from twosee/swoole-coroutine
177e7ef0df69: Already exists
66ec699db42d: Pull complete
9af6d87fd347: Pull complete
62d170e11208: Pull complete
11090682e442: Pull complete
e082801d238e: Pull complete
60bdd517265c: Pull complete
70d4819ea554: Pull complete
8263a41e21ee: Pull complete
Pulling inotify (twosee/swoole-coroutine:inotify)...
inotify: Pulling from twosee/swoole-coroutine
177e7ef0df69: Already exists
9bf89f2eda24: Pull complete
350207dcf1b7: Pull complete
a8a33d96b4e7: Pull complete
a6bbe73cd4ac: Pull complete
7437bed677a4: Pull complete
224469450987: Pull complete
77146cd968da: Pull complete
1fd14aaf5f1e: Pull complete
3c73c6f205be: Pull complete
8bbfe2e0c433: Pull complete
6e0cd798809a: Pull complete
ad07a86624b2: Pull complete
7a3c9d988d91: Pull complete
7d7f69de90f6: Pull complete
fa7fb5610247: Pull complete
Creating docker_mysql_1   ... done
Creating docker_redis_1   ... done
Creating docker_inotify_1 ... done
Creating docker_swoole_1  ... done
Attaching to docker_inotify_1, docker_mysql_1, docker_redis_1, docker_swoole_1
inotify_1  | /bin/bash: inotify.sh: No such file or directory
mysql_1    | Initializing database
mysql_1    | 2019-04-17T02:23:36.649424Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
mysql_1    | 2019-04-17T02:23:36.686970Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.13) initializing of server in progress as process 30
docker_inotify_1 exited with code 127
inotify_1  | /bin/bash: inotify.sh: No such file or directory`

**Comment by twose** [comment]
亲 不能无脑照搬 inotify需要自己写监控脚本才行
